apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE$VERSION
  labels:
    version: v1
    app: $SERVICE$VERSION
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $SERVICE$VERSION
      version: v1
  template:
    metadata:
      labels:
        version: v1
        app: $SERVICE$VERSION
    spec:
      serviceAccountName: egeo-$SERVICE-$VERSION
      containers:
        - image: joaollr/$SERVICE:$ACTUAL_VERSION
          imagePullPolicy: Always
          name: $SERVICE$VERSION
          ports:
            - containerPort: 8082
          volumeMounts:
            - mountPath: /data
              name: $SERVICE
              #   - mountPath: /app/log
              #     name: $SERVICE
              #   - mountPath: /build/app
              #     name: $SERVICE
              #     # resources: 
              #     #   requests:
              #     #     memory: "512Mi"    
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: $SERVICE
          persistentVolumeClaim:
            claimName: $SERVICE
